### ISSUE TITLE
Issues getting csrmesh to run

### ISSUE THREAD

**Issue by creising** [nkaminski/csrmesh#9]
I might be doing something wrong, so I apologize in advance is this has an obvious solution. When I run the csrmesh-cli, I get the following error:

File "/usr/local/lib/python3.4/dist-packages/csrmesh-0.5.1-py3.4.egg/csrmesh/**init**.py", line 12, in network_key
    pin2 = pin.encode('ascii') + b'\x00MCP'
AttributeError: 'int' object has no attribute 'encode'

The command: csrmesh-cli --pin 6789 --dest E0:34:E4:06:16:9D --level 255

Any insight would be much appreciated. Thanks for the cool project!

**Comment by creising** [comment]
For what it is worth I got it working with version 0.5. I think the address in my original post was too short, but it was still throwing error that did not seem to be related to that.

**Comment by nkaminski** [comment]
Sorry about my slow response, had a large robotics competition that consumed much of my free time. Issue identified, bug was introduced when refactoring Python 2.7 compatibility and is fixed in 0.6.
